on: [push]

jobs:
  send-message:
    runs-on: ubuntu-latest
    name: Send message via Matrix
    steps:
    - name: Send message to test channel
      id: matrix-chat-message
      uses: fadenb/matrix-chat-message@v0.0.6
      with:
        homeserver: yaml.ems.host
        token: ${{ secrets.MATRIX_TOKEN }}
        channel: '!lUyCvwvbttMFxCVMLM:yaml.io'
        message: |
          ```
          action: ${{ github.action }}
          actor:  ${{ github.actor }}
          repo:   ${{ github.repository }}
          commit: ${{ github.sha }}
          branch: $(( github.ref }}
          ```
