name: yaml-spec Repository Testing

on:
  push:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: make verbose test

# TODO: Make this on demand.
#     - uses: mxschmitt/action-tmate@v3
