name: yaml-spec Repository Testing

on:
  push:
  pull_request:
    types: [opened]

jobs:
  test-make-targets:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1

    - name: Run `make test`
      run:  make test
